### ISSUE TITLE
Not a fully functioning workaround

### ISSUE THREAD

**Issue by anonymouz4** [Siguza/hsp4#1]
All mach_* and vm_* apis, except `pid_for_task`, will result in a instant kernel crash.

The cause isn't the remapping, since I also crashes when putting the orig task in `host->special[4]`
**It will crash exactly [here](https://github.com/chr1s0x1/xnu-6153.11.26/blob/a99135cd9d58fa070aebc094c82b1ac2c62b179b/osfmk/kern/zalloc.c#L658)**

It's called by `convert_port_to_task_locked [inlined] task_conversion_eval`

It seems to be something similar to what Apple introduced in iOS 13, where zone_require checks if the port originates in the zone numbered zindex..

**Comment by Siguza** [comment]
What makes you think `task_info` is at all populated?

Also, High Sierra is the last version I tried this on. I'll have to look into Mojave and Catalina...

**Comment by anonymouz4** [comment]
I've tried overriding the return value of `task_conversion_eval` from `osfmk/kern/ipc_tt.c` to pass the `task=kernel_task` checks in all the mach_* apis, but still doesn't work; it seems there're some other checks also in place..

**Comment by anonymouz4** [comment]
**Update:**
Fixed it by just nop'ing out the `zone_require` calls in the inlined task_conversion_eval funcs.
Its not perfect but works; might post it on my repo

**Comment by Siguza** [comment]
Ahh of course, that's a thing... I'll have to see what I can do about that.

**Comment by anonymouz4** [comment]
See [0x0XDev/UserKernelAccess](https://github.com/0x0XDev/UserKernelAccess) for my temporary fix
